### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by ghost** [xuzhipengnt/IPClient-for-GXNU#1]
应该使用哪个版本的PY
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ipclient_gxnu-master\ipclient_python\macopen.py", line 65, in <module>
    send_handshake(mac,ip,isp)
  File "C:\Users\Administrator\Downloads\ipclient_gxnu-master\ipclient_python\macopen.py", line 14, in send_handshake
    localInfo[0]='1'
TypeError: an integer is required

**Comment by xuzhipengnt** [comment]
2.7版本
你们桂电的的server地址是172.16.1.1 
https://github.com/xuzhipengnt/ipclient_gxnu/tree/master/macopen_guet

**Comment by ghost** [comment]
我试过2.7版，和3.5版，都出现以上错误。
服务器确实是172.16.1.1。

**Comment by xuzhipengnt** [comment]
https://github.com/xuzhipengnt/ipclient_gxnu/tree/master/macopen_guet
localInfo[0]是用户名，一般来说任意都行，可能windows不支持这样写，我改成了0x61

**Comment by ghost** [comment]
[10, 21, 124, 222]
60

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ipclient_gxnu-master\ipclient_python\macopen.py", line 65, in <module>
    send_handshake(mac,ip,isp)
  File "C:\Users\Administrator\Downloads\ipclient_gxnu-master\ipclient_python\macopen.py", line 36, in send_handshake
    ESI=numpy.int32(ECX<<5)
OverflowError: Python int too large to convert to C long
